version: '3.4'
services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    image: golang
    container_name: go-store
    ports:
      - 9000:9000
    expose:
      - 9000
    networks:
      net:
        ipv4_address: 172.20.0.4

  mysql:
    image: mysql:latest
    container_name: mysql-go
    env_file: "./.env"
    ports: 
      - 3305:3306
    expose:
      - 3305
    command: [--default-authentication-plugin=mysql_native_password]
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
    networks:
      net:
        ipv4_address: 172.20.0.5

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24