-- MySQL Script generated by MySQL Workbench
-- qui 15 out 2020 21:37:30 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema go_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema go_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `go_store` ;
USE `go_store` ;

-- -----------------------------------------------------
-- Table `go_store`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go_store`.`store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(45) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `company_name` VARCHAR(120) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `go_store`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go_store`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_store` INT NOT NULL,
  `nick_name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `cash` DECIMAL NULL,
  `birth_date` DATE NOT NULL,
  PRIMARY KEY (`id`, `id_store`),
  INDEX `fk_client_store1_idx` (`id_store` ASC),
  CONSTRAINT `fk_client_store1`
    FOREIGN KEY (`id_store`)
    REFERENCES `go_store`.`store` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `go_store`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go_store`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_store` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `id_store`),
  INDEX `fk_products_store_idx` (`id_store` ASC),
  CONSTRAINT `fk_products_store`
    FOREIGN KEY (`id_store`)
    REFERENCES `go_store`.`store` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `go_store`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go_store`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `go_store`.`product_amount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go_store`.`product_amount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_product` INT NOT NULL,
  `id_product_store` INT NOT NULL,
  `id_client` INT NOT NULL,
  `id_client_store` INT NOT NULL,
  `amount` INT NULL,
  PRIMARY KEY (`id`, `id_product`, `id_product_store`, `id_client`, `id_client_store`),
  INDEX `fk_product_amount_product1_idx` (`id_product` ASC, `id_product_store` ASC),
  INDEX `fk_product_amount_client1_idx` (`id_client` ASC, `id_client_store` ASC),
  CONSTRAINT `fk_product_amount_product1`
    FOREIGN KEY (`id_product` , `id_product_store`)
    REFERENCES `go_store`.`product` (`id` , `id_store`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_amount_client1`
    FOREIGN KEY (`id_client` , `id_client_store`)
    REFERENCES `go_store`.`client` (`id` , `id_store`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `go_store`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go_store`.`history` (
  `id` INT NOT NULL,
  `id_status` INT NOT NULL,
  `id_product_amount` INT NOT NULL,
  `id_product_amount_product` INT NOT NULL,
  `id_product_amount_product_store` INT NOT NULL,
  `id_product_amount_client` INT NOT NULL,
  `id_product_amount_client_store` INT NOT NULL DEFAULT 0,
  `transiction_date` DATE NOT NULL,
  `value_paid` DECIMAL NULL,
  `value_transaction` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `id_status`, `id_product_amount`, `id_product_amount_product`, `id_product_amount_product_store`, `id_product_amount_client`, `id_product_amount_client_store`),
  INDEX `fk_history_status1_idx` (`id_status` ASC),
  INDEX `fk_history_product_amount1_idx` (`id_product_amount` ASC, `id_product_amount_product` ASC, `id_product_amount_product_store` ASC, `id_product_amount_client` ASC, `id_product_amount_client_store` ASC),
  CONSTRAINT `fk_history_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `go_store`.`status` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_history_product_amount1`
    FOREIGN KEY (`id_product_amount` , `id_product_amount_product` , `id_product_amount_product_store` , `id_product_amount_client` , `id_product_amount_client_store`)
    REFERENCES `go_store`.`product_amount` (`id` , `id_product` , `id_product_store` , `id_client` , `id_client_store`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SET GLOBAL FOREIGN_KEY_CHECKS=0;
